{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.zabbixAgent2;

  inherit (pkgs) zabbix;

  # State directory for persistent data (shared with other zabbix services)
  stateDir = "/var/lib/zabbix";

  # Auto-generated PSK file path
  autoGeneratedPskFile = "${stateDir}/psk";

  # Effective PSK settings (with auto-generation defaults)
  effectivePskFile =
    if cfg.tls.psk.autoGenerate.enable then autoGeneratedPskFile
    else cfg.tls.psk.file;

  effectivePskIdentity =
    if cfg.tls.psk.autoGenerate.enable && cfg.tls.psk.identity == null then
      "PSK_${if cfg.hostname != null then cfg.hostname else config.networking.hostName}"
    else cfg.tls.psk.identity;

  # PSK bytes based on bits
  pskBytes = {
    "128" = 16;
    "256" = 32;
    "512" = 64;
  }.${toString cfg.tls.psk.autoGenerate.bits};

  # Helper to convert nested attrs to flat "Dot.Notation=value" format
  flattenAttrs = prefix: attrs:
    flatten (mapAttrsToList (name: value:
      let
        newPrefix = if prefix == "" then name else "${prefix}.${name}";
      in
      if isAttrs value && !(value ? _type) then
        flattenAttrs newPrefix value
      else
        { name = newPrefix; inherit value; }
    ) attrs);

  # Convert a value to config string
  valueToString = value:
    if isList value then concatStringsSep "," (map toString value)
    else if isBool value then (if value then "1" else "0")
    else toString value;

  # Generate main config entries
  configEntries = flattenAttrs "" cfg.settings;

  # Plugin configuration - flattened to Plugins.* format
  pluginEntries = flattenAttrs "Plugins" cfg.plugins.settings;

  # Combine all config
  allEntries = configEntries ++ pluginEntries;

  configFile = pkgs.writeText "zabbix_agent2.conf" (
    concatStringsSep "\n" (
      map ({ name, value }: "${name}=${valueToString value}") allEntries
    )
    + optionalString (cfg.plugins.extraConfig != "") "\n${cfg.plugins.extraConfig}"
  );

in

{
  ###### interface

  options = {

    services.zabbixAgent2 = {
      enable = mkEnableOption "the Zabbix Agent 2";

      package = mkOption {
        type = types.package;
        default = zabbix.agent2;
        defaultText = literalExpression "pkgs.zabbix.agent2";
        description = "The Zabbix Agent 2 package to use.";
      };

      extraPackages = mkOption {
        type = types.listOf types.package;
        default = with pkgs; [ nettools ];
        defaultText = literalExpression "with pkgs; [ nettools ]";
        description = ''
          Packages to be added to the Zabbix Agent 2 {env}`PATH`.
          Typically used to add executables for scripts, but can be anything.
        '';
      };

      server = mkOption {
        type = types.str;
        description = ''
          The IP address or hostname of the Zabbix server to connect to.
        '';
        example = "127.0.0.1";
      };

      serverActive = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = ''
          The IP address or hostname of the Zabbix server for active checks.
          If not set, defaults to the value of `server`.
        '';
        example = "zabbix.example.com:10051";
      };

      hostname = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = ''
          Unique hostname. Required for active checks. If not defined,
          it will be set from HostnameItem.
        '';
      };

      listen = {
        ip = mkOption {
          type = types.nullOr types.str;
          default = null;
          example = "192.168.1.100";
          description = ''
            IP address that the agent should listen on.

            Note: Zabbix Agent 2 has a quirk where it cannot accept
            configuration files that explicitly set ListenIP to 0.0.0.0
            (the default). Leave as null to listen on all interfaces.
          '';
        };

        port = mkOption {
          type = types.port;
          default = 10050;
          description = ''
            Port the agent will listen on for connections from the server.
          '';
        };
      };

      openFirewall = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Open ports in the firewall for the Zabbix Agent 2.
        '';
      };

      settings = mkOption {
        type = with types; attrsOf (oneOf [ int str bool (listOf str) ]);
        default = { };
        description = ''
          Zabbix Agent 2 configuration. Refer to
          <https://www.zabbix.com/documentation/current/en/manual/appendix/config/zabbix_agent2>
          for details on supported values.

          Note: Plugin settings should go in `plugins.settings` instead.
        '';
        example = literalExpression ''
          {
            DebugLevel = 3;
            Timeout = 10;
            BufferSend = 5;
            BufferSize = 100;
          }
        '';
      };

      # Plugin configuration
      plugins = {
        settings = mkOption {
          type = with types; attrsOf (oneOf [
            int
            str
            bool
            (listOf str)
            (attrsOf (oneOf [ int str bool (listOf str) (attrsOf anything) ]))
          ]);
          default = { };
          description = ''
            Plugin settings for Zabbix Agent 2. These will be converted to
            `Plugins.*` configuration entries.
          '';
          example = literalExpression ''
            {
              # MySQL monitoring (sessions-based)
              Mysql.Sessions.mydb = {
                Uri = "tcp://localhost:3306";
                User = "zabbix";
                Password = "secret";
              };

              # PostgreSQL monitoring
              PostgreSQL.Sessions.pgmain = {
                Uri = "postgresql://localhost:5432";
                User = "zabbix";
                Password = "secret";
                Database = "postgres";
              };

              # Redis monitoring
              Redis.Sessions.local = {
                Uri = "tcp://localhost:6379";
              };

              # Docker monitoring
              Docker.Endpoint = "unix:///var/run/docker.sock";

              # Custom timeout for specific plugin
              Mysql.Timeout = 10;
            }
          '';
        };

        extraConfig = mkOption {
          type = types.lines;
          default = "";
          description = ''
            Extra raw configuration for Zabbix Agent 2 plugins.
            This is appended verbatim to the configuration file.
          '';
          example = ''
            # Include additional configuration
            Include=/etc/zabbix/zabbix_agent2.d/*.conf
          '';
        };
      };

      # Control socket for runtime commands
      controlSocket = mkOption {
        type = types.nullOr types.path;
        default = "/run/zabbix/agent2.sock";
        description = ''
          The control socket path used for runtime commands.
          This allows commands like `zabbix_agent2 -R log_level_increase`.
          Set to null to disable.
        '';
      };

      # Status port for internal metrics
      statusPort = mkOption {
        type = types.nullOr types.port;
        default = null;
        example = 31999;
        description = ''
          Port for the internal HTTP server providing agent metrics.
          Access metrics at http://localhost:<port>/status.
          Set to null to disable.
        '';
      };

      user = mkOption {
        type = types.str;
        default = "zabbix";
        description = "User under which the Zabbix Agent 2 runs.";
      };

      group = mkOption {
        type = types.str;
        default = "zabbix";
        description = "Group under which the Zabbix Agent 2 runs.";
      };

      # TLS/Encryption configuration
      tls = {
        enable = mkOption {
          type = types.bool;
          default = false;
          description = ''
            Enable TLS encryption using auto-generated PSK.
            This is a convenience option that sets:
            - `tls.connect = "psk"`
            - `tls.accept = [ "psk" ]`
            - `tls.psk.autoGenerate.enable = true`

            After enabling, run `sudo zabbix-agent2-psk show` to get the
            PSK for configuring your Zabbix server.

            For more control, use the individual tls.* options instead.
          '';
        };

        connect = mkOption {
          type = types.enum [ "unencrypted" "psk" "cert" ];
          default = "unencrypted";
          description = ''
            How the agent should connect to the server for active checks.
            - `unencrypted` - No encryption
            - `psk` - Use pre-shared key
            - `cert` - Use TLS certificates
          '';
        };

        accept = mkOption {
          type = types.listOf (types.enum [ "unencrypted" "psk" "cert" ]);
          default = [ "unencrypted" ];
          example = [ "psk" ];
          description = ''
            What type of incoming connections to accept from the server.
            Can specify multiple values for flexibility.
          '';
        };

        psk = {
          autoGenerate = {
            enable = mkEnableOption ''
              automatic PSK generation. When enabled, a PSK will be
              automatically generated on first boot and stored persistently.
              The PSK identity will be derived from the hostname if not set.

              Use `zabbix-agent2-psk show` to retrieve the PSK for configuring
              your Zabbix server/proxy
            '';

            bits = mkOption {
              type = types.enum [ 128 256 512 ];
              default = 256;
              description = ''
                PSK key strength in bits.
                - 128 bits = 32 hex characters
                - 256 bits = 64 hex characters (recommended)
                - 512 bits = 128 hex characters
              '';
            };
          };

          identity = mkOption {
            type = types.nullOr types.str;
            default = null;
            example = "PSK_agent_webserver01";
            description = ''
              PSK identity string. Must match the identity configured
              on the Zabbix server for this host.

              If `autoGenerate.enable` is true and this is null, the identity
              will be automatically set to `PSK_<hostname>`.
            '';
          };

          file = mkOption {
            type = types.nullOr types.path;
            default = null;
            example = "/run/secrets/zabbix-psk";
            description = ''
              Path to the file containing the pre-shared key.
              The key must be a hexadecimal string (0-9, a-f)
              between 32 and 128 characters (representing 128-512 bits).

              If `autoGenerate.enable` is true, this will be automatically
              set to a path in the state directory.

              Otherwise, this file should be managed separately with proper
              permissions (e.g., via agenix, sops-nix, or systemd credentials).
              The file must be readable by the zabbix-agent2 user.
            '';
          };
        };

        cert = {
          caFile = mkOption {
            type = types.nullOr types.path;
            default = null;
            example = "/etc/zabbix/ssl/ca.crt";
            description = ''
              Path to the CA certificate file for verifying server certificates.
            '';
          };

          certFile = mkOption {
            type = types.nullOr types.path;
            default = null;
            example = "/etc/zabbix/ssl/agent.crt";
            description = ''
              Path to the agent's TLS certificate file.
            '';
          };

          keyFile = mkOption {
            type = types.nullOr types.path;
            default = null;
            example = "/etc/zabbix/ssl/agent.key";
            description = ''
              Path to the agent's TLS private key file.
            '';
          };

          serverCertIssuer = mkOption {
            type = types.nullOr types.str;
            default = null;
            description = ''
              Allowed server certificate issuer (for additional validation).
            '';
          };

          serverCertSubject = mkOption {
            type = types.nullOr types.str;
            default = null;
            description = ''
              Allowed server certificate subject (for additional validation).
            '';
          };
        };
      };
    };

  };

  ###### implementation

  config = mkIf cfg.enable {

    assertions = [
      {
        assertion = cfg.listen.ip != "0.0.0.0";
        message = ''
          Zabbix Agent 2 cannot accept configuration files that explicitly
          set ListenIP to 0.0.0.0. Leave services.zabbixAgent2.listen.ip
          as null to listen on all interfaces.
        '';
      }
      {
        assertion = (cfg.tls.connect == "psk" || elem "psk" cfg.tls.accept) ->
          (cfg.tls.psk.autoGenerate.enable || (cfg.tls.psk.identity != null && cfg.tls.psk.file != null));
        message = ''
          When using PSK encryption (tls.connect = "psk" or "psk" in tls.accept),
          either enable tls.psk.autoGenerate.enable, or set both tls.psk.identity
          and tls.psk.file manually.
        '';
      }
      {
        assertion = (cfg.tls.connect == "cert" || elem "cert" cfg.tls.accept) ->
          (cfg.tls.cert.caFile != null && cfg.tls.cert.certFile != null && cfg.tls.cert.keyFile != null);
        message = ''
          When using certificate encryption (tls.connect = "cert" or "cert" in tls.accept),
          tls.cert.caFile, tls.cert.certFile, and tls.cert.keyFile must all be set.
        '';
      }
    ];

    # Apply defaults when tls.enable is used
    services.zabbixAgent2.tls = mkIf cfg.tls.enable {
      connect = mkDefault "psk";
      accept = mkDefault [ "psk" ];
      psk.autoGenerate.enable = mkDefault true;
    };

    services.zabbixAgent2.settings = mkMerge [
      {
        Server = cfg.server;
        ServerActive = if cfg.serverActive != null then cfg.serverActive else cfg.server;
        ListenPort = cfg.listen.port;
        LogType = "console";
      }
      (mkIf (cfg.hostname != null) {
        Hostname = cfg.hostname;
      })
      (mkIf (cfg.listen.ip != null) {
        ListenIP = cfg.listen.ip;
      })
      (mkIf (cfg.controlSocket != null) {
        ControlSocket = cfg.controlSocket;
      })
      (mkIf (cfg.statusPort != null) {
        StatusPort = cfg.statusPort;
      })
      # TLS settings
      (mkIf (cfg.tls.connect != "unencrypted") {
        TLSConnect = cfg.tls.connect;
      })
      (mkIf (cfg.tls.accept != [ "unencrypted" ]) {
        TLSAccept = cfg.tls.accept;
      })
      # PSK settings (use effective values for auto-generation support)
      (mkIf (effectivePskIdentity != null) {
        TLSPSKIdentity = effectivePskIdentity;
      })
      (mkIf (effectivePskFile != null) {
        TLSPSKFile = effectivePskFile;
      })
      # Certificate settings
      (mkIf (cfg.tls.cert.caFile != null) {
        TLSCAFile = cfg.tls.cert.caFile;
      })
      (mkIf (cfg.tls.cert.certFile != null) {
        TLSCertFile = cfg.tls.cert.certFile;
      })
      (mkIf (cfg.tls.cert.keyFile != null) {
        TLSKeyFile = cfg.tls.cert.keyFile;
      })
      (mkIf (cfg.tls.cert.serverCertIssuer != null) {
        TLSServerCertIssuer = cfg.tls.cert.serverCertIssuer;
      })
      (mkIf (cfg.tls.cert.serverCertSubject != null) {
        TLSServerCertSubject = cfg.tls.cert.serverCertSubject;
      })
    ];

    networking.firewall.allowedTCPPorts = mkIf cfg.openFirewall [
      cfg.listen.port
    ];

    users.users.${cfg.user} = {
      description = mkDefault "Zabbix daemon user";
      isSystemUser = mkDefault true;
      group = mkDefault cfg.group;
    };

    users.groups.${cfg.group} = { };

    # Create runtime directories
    systemd.tmpfiles.rules = [
      "d '/run/zabbix' 0750 ${cfg.user} ${cfg.group} - -"
    ];

    systemd.services.zabbix-agent2 = {
      description = "Zabbix Agent 2";
      wantedBy = [ "multi-user.target" ];
      after = [ "network.target" ];
      path = [ "/run/wrappers" pkgs.openssl ] ++ cfg.extraPackages;

      preStart = mkIf cfg.tls.psk.autoGenerate.enable ''
        # Generate PSK if it doesn't exist
        if [ ! -f "${autoGeneratedPskFile}" ]; then
          echo "Generating new Zabbix Agent 2 PSK (${toString cfg.tls.psk.autoGenerate.bits} bits)..."
          ${pkgs.openssl}/bin/openssl rand -hex ${toString pskBytes} > "${autoGeneratedPskFile}"
          chmod 0400 "${autoGeneratedPskFile}"
          echo "PSK generated and saved to ${autoGeneratedPskFile}"
          echo ""
          echo "===== IMPORTANT ====="
          echo "Configure your Zabbix server/proxy with:"
          echo "  PSK Identity: ${effectivePskIdentity}"
          echo "  PSK: $(cat "${autoGeneratedPskFile}")"
          echo ""
          echo "You can also run: zabbix-agent2-psk show"
          echo "====================="
        fi
      '';

      serviceConfig = {
        ExecStart = "${cfg.package}/bin/zabbix_agent2 --foreground --config ${configFile}";
        Restart = "on-failure";
        RestartSec = "10s";

        User = cfg.user;
        Group = cfg.group;

        # Runtime directory
        RuntimeDirectory = "zabbix";
        RuntimeDirectoryMode = "0750";

        # State directory for persistent data
        StateDirectory = "zabbix";
        StateDirectoryMode = "0750";

        # Hardening options
        CapabilityBoundingSet = [
          ""  # Drop all capabilities by default
          # Add back specific ones if needed:
          # "CAP_NET_RAW"  # For ICMP checks
        ];
        DevicePolicy = "closed";
        LockPersonality = true;
        MemoryDenyWriteExecute = true;
        NoNewPrivileges = true;
        PrivateDevices = true;
        PrivateTmp = true;
        ProtectClock = true;
        ProtectControlGroups = true;
        ProtectHome = true;
        ProtectHostname = true;
        ProtectKernelLogs = true;
        ProtectKernelModules = true;
        ProtectKernelTunables = true;
        ProtectSystem = "strict";
        RemoveIPC = true;
        RestrictAddressFamilies = [ "AF_INET" "AF_INET6" "AF_UNIX" ];
        RestrictNamespaces = true;
        RestrictRealtime = true;
        RestrictSUIDSGID = true;
        SystemCallArchitectures = "native";
        SystemCallFilter = [
          "@system-service"
          "~@privileged"
          "~@resources"
        ];
      };
    };

    # Helper script for PSK management (shared by agent and proxy)
    environment.systemPackages = mkIf cfg.tls.psk.autoGenerate.enable [
      (pkgs.writeShellScriptBin "zabbix-psk" ''
        set -euo pipefail

        PSK_FILE="${autoGeneratedPskFile}"
        PSK_IDENTITY="${effectivePskIdentity}"

        usage() {
          echo "Zabbix PSK Management"
          echo ""
          echo "Usage: zabbix-psk <command>"
          echo ""
          echo "Commands:"
          echo "  show        Show PSK identity and key (requires root)"
          echo "  identity    Show only the PSK identity"
          echo "  json        Output as JSON (for automation)"
          echo "  regenerate  Generate a new PSK (requires root, restarts agent)"
          echo ""
        }

        check_root() {
          if [ "$(id -u)" -ne 0 ]; then
            echo "Error: This command requires root privileges" >&2
            exit 1
          fi
        }

        case "''${1:-}" in
          show)
            check_root
            if [ ! -f "$PSK_FILE" ]; then
              echo "Error: PSK file not found. Start the zabbix-agent2 service first." >&2
              exit 1
            fi
            echo "PSK Identity: $PSK_IDENTITY"
            echo "PSK: $(cat "$PSK_FILE")"
            ;;
          identity)
            echo "$PSK_IDENTITY"
            ;;
          json)
            check_root
            if [ ! -f "$PSK_FILE" ]; then
              echo '{"error": "PSK file not found"}' >&2
              exit 1
            fi
            echo "{\"identity\": \"$PSK_IDENTITY\", \"psk\": \"$(cat "$PSK_FILE")\"}"
            ;;
          regenerate)
            check_root
            echo "Removing existing PSK..."
            rm -f "$PSK_FILE"
            echo "Restarting zabbix-agent2 to generate new PSK..."
            systemctl restart zabbix-agent2
            sleep 2
            echo ""
            echo "New PSK generated:"
            "$0" show
            ;;
          *)
            usage
            exit 1
            ;;
        esac
      '')
    ];

  };

  meta.maintainers = [ ];
}
